FROM node:20-alpine

# Instala o FFmpeg e ffprobe no Alpine
RUN apk add --no-cache ffmpeg

WORKDIR /home/node/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "run", "start:prod"]